/**
 * Downloads the four font families from Google Fonts into public/fonts/ and
 * writes fonts.css to match. Run it after changing which families or weights
 * the site uses; index.css imports the result.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * No dependencies.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = `${ROOT}/public/fonts`;

/* A browser UA is what makes the API answer with woff2 rather than ttf. */
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

/* The site is English and Arabic only — every other subset Google offers
   (cyrillic, vietnamese, greek…) is weight nobody here will ever download. */
const KEEP = new Set(["latin", "latin-ext", "arabic"]);

const FAMILIES = [
  { name: "Cormorant Garamond", query: "Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400" },
  { name: "Jost", query: "Jost:wght@300;400;500" },
  { name: "Amiri", query: "Amiri:wght@400;700" },
  { name: "IBM Plex Sans Arabic", query: "IBM+Plex+Sans+Arabic:wght@200;300;400;500" },
];

const slug = (s) => s.toLowerCase().replace(/\s+/g, "-");

mkdirSync(OUT, { recursive: true });

const faces = [];
let bytes = 0;
let skipped = 0;

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
    if (!r.ok) throw new Error(`${family.name}: HTTP ${r.status}`);
    return r.text();
  });

  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g)];
  if (!blocks.length) throw new Error(`${family.name}: no @font-face blocks parsed`);

  for (const [, subset, body] of blocks) {
    if (!KEEP.has(subset)) {
      skipped++;
      continue;
    }

    const pick = (prop) => body.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim();
    const style = pick("font-style");
    const weight = pick("font-weight");
    const range = pick("unicode-range");
    const src = body.match(/url\(([^)]+)\)/)?.[1];
    if (!src || !style || !weight || !range) throw new Error(`${family.name}/${subset}: incomplete`);

    const file = `${slug(family.name)}-${weight}-${style}-${subset}.woff2`;
    const buf = Buffer.from(
      await fetch(src, { headers: { "User-Agent": UA } }).then((r) => r.arrayBuffer()),
    );
    writeFileSync(`${OUT}/${file}`, buf);
    bytes += buf.length;

    faces.push({ family: family.name, style, weight, range, file, subset, size: buf.length });
  }
}

const css = `/* ------------------------------------------------------------------
   Self-hosted fonts. Generated by scripts/fetch-fonts.mjs — do not edit.

   Served from this origin rather than Google's, so the browser no longer has
   to fetch a stylesheet from fonts.googleapis.com and only then discover the
   font files behind it.

   All four families are under the SIL Open Font License 1.1, which permits
   self-hosting. See public/fonts/LICENSE.md.
   ------------------------------------------------------------------ */

${faces
  .map(
    (f) => `/* ${f.subset} */
@font-face {
  font-family: "${f.family}";
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url("/fonts/${f.file}") format("woff2");
  unicode-range: ${f.range};
}`,
  )
  .join("\n\n")}
`;

writeFileSync(`${ROOT}/fonts.css`, css, "utf8");

const byFamily = {};
for (const f of faces) byFamily[f.family] = (byFamily[f.family] ?? 0) + 1;
console.log(`${faces.length} files, ${(bytes / 1024).toFixed(0)} KB total (${skipped} unused subsets skipped)`);
for (const [name, n] of Object.entries(byFamily)) console.log(`  ${name.padEnd(22)} ${n} files`);
